from setuptools import setup, find_packages
import sys, os

version = '0.1'

setup(name='parsewkt',
      version=version,
      description="WKT Parser",
      long_description="""\
A Parser for WKT generated by grako""",
      classifiers=[], # Get strings from http://pypi.python.org/pypi?%3Aaction=list_classifiers
      keywords='WKT GIS Spatial',
      author='Christian Ledermann',
      author_email='christian.ledermann@gmail.com',
      url='',
      license='LGPL',
      packages=find_packages(exclude=['ez_setup', 'examples', 'tests']),
      include_package_data=True,
      zip_safe=False,
      install_requires=[
          # -*- Extra requirements: -*-
      ],
      entry_points="""
      # -*- Entry points: -*-
      """,
      )
